# Generated by Django 2.0.6 on 2018-07-29 07:22
from django.contrib.auth.hashers import make_password
from django.db import migrations

def add_employee(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Employee = apps.get_model('employee', 'Employee')
    try:
        employee = Employee.objects.get(username= 'employee', email = 'employee@employee.com')
    except:
        employee = Employee(username= 'employee', email = 'employee@employee.com', current_salary = 20)
        employee.password = make_password('employeeemployee')
        employee.save()

def remove_employee(apps,schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    try:
        employee = Employee.objects.get(username= 'employee')
        employee.delete()
    except:
        pass    
    
class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('main', '0006_auto_20180729_0709')
    ]

    operations = [
        migrations.RunPython(add_employee, remove_employee)
    ]
