# Generated by Django 2.0.7 on 2018-08-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180729_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeereview',
            name='new_status',
            field=models.IntegerField(choices=[(0, 'accepted'), (1, 'rejected'), (2, 'pending'), (3, 'failed'), (4, 'reported')], default=0),
        ),
    ]
