# Generated by Django 2.0.7 on 2018-08-09 07:05

from django.db import migrations

def add_EmployeeReview(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    Request = apps.get_model('customer', 'Request')
    EmployeeReview = apps.get_model('employee', 'EmployeeReview')
    employee  = Employee.objects.get(username= 'employee', email = 'employee@employee.com')
    requests = Request.objects.filter(status = 2)
    print(len(requests))
    employeeReview = EmployeeReview(request = requests[0], employee = employee, new_status = 0)
    employeeReview.save()
    employeeReview.request.status = 0
    employeeReview.request.save()
    employeeReview = EmployeeReview(request = requests[1], employee = employee, new_status = 1)
    employeeReview.save()
    employeeReview.request.status = 1
    employeeReview.request.save()
    employeeReview = EmployeeReview(request = requests[2], employee = employee, new_status = 4)
    employeeReview.request.status = 4
    employeeReview.request.save()
    employeeReview.save()
    employeeReview = EmployeeReview(request = requests[3], employee = employee, new_status = 4)
    employeeReview.save()
    employeeReview.request.status = 4
    employeeReview.request.save()
def remove_EmployeeReview(apps,schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    EmployeeReview = apps.get_model('employee', 'EmployeeReview')
    employee = Employee.objects.get(username= 'employee', email = 'employee@employee.com')
    reviews = EmployeeReview.objects.filter(employee = employee)
    reviews.delete()

class Migration(migrations.Migration):
    dependencies = [
        ('employee', '0003_employeereview_new_status'),
    ]
    operations = [
        migrations.RunPython(add_EmployeeReview, remove_EmployeeReview),
    ]
