# Generated by Django 2.0.3 on 2018-08-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='request',
            name='dest_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dest_user', to='main.Wallet_User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dest_wallet',
            field=models.IntegerField(blank=True, choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='fianl_wallet',
            field=models.IntegerField(blank=True, choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='final_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_user', to='main.Wallet_User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='profitRate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='source_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_user', to='main.Wallet_User'),
        ),
        migrations.AlterField(
            model_name='request',
            name='source_wallet',
            field=models.IntegerField(blank=True, choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')], default=0),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'accepted'), (1, 'rejected'), (2, 'pending'), (3, 'failed'), (4, 'reported')], default=2),
        ),
    ]
