# Generated by Django 2.0.6 on 2018-06-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('manager', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TOEFL',
            new_name='TOFEL',
        ),
    ]
