# Generated by Django 2.0.6 on 2018-06-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180613_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.Request')),
                ('wallet', models.IntegerField(choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('customer.request',),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.Request')),
                ('source', models.IntegerField(choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')])),
                ('destination', models.IntegerField(choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('customer.request',),
        ),
        migrations.RemoveField(
            model_name='costumerwalletchanges',
            name='request',
        ),
        migrations.RemoveField(
            model_name='customerwalletcharge',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerwallettransfer',
            name='customer',
        ),
        migrations.DeleteModel(
            name='CostumerWalletChanges',
        ),
        migrations.DeleteModel(
            name='CustomerWalletCharge',
        ),
        migrations.DeleteModel(
            name='CustomerWalletTransfer',
        ),
    ]
