# Generated by Django 2.0.7 on 2018-08-07 16:06

from django.db import migrations


def add_charge(apps, schema_editor):
    Customer = apps.get_model('customer', 'Customer')
    Charge = apps.get_model('customer', 'Charge')
    customer = Customer.objects.get(username= 'customer', email = 'customer@customer.com')
    for i in range(0,5):
        charge = Charge(customer = customer, currency = 0, amount = i*10, wallet = 0)
        customer.rial_credit += i*10
        charge.save()
    customer.save()
def remove_charge(apps,schema_editor):
    Customer = apps.get_model('customer', 'Customer')
    Charge = apps.get_model('customer', 'Charge')
    customer = Customer.objects.get(username= 'customer', email = 'customer@customer.com')
    Customer = apps.get_model('customer', 'Customer')
    charges = Customer.objects.get(customer = customer)
    charges.delete()
    


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20180807_1624'),
    ]

    operations = [
        migrations.RunPython(add_charge, remove_charge)
    ]
