# Generated by Django 2.0.7 on 2018-08-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20180807_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charge',
            options={},
        ),
        migrations.AlterModelOptions(
            name='exchange',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foreigntrans',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ibt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='internaltrans',
            options={},
        ),
        migrations.AlterModelOptions(
            name='langtest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tofel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='universitytrans',
            options={},
        ),
        migrations.AlterModelOptions(
            name='unknowntrans',
            options={},
        ),
    ]
