# Generated by Django 2.0.3 on 2018-06-03 22:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWalletChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'request submit'), (2, 'request profit'), (3, 'request failure'), (4, 'request failure profit'), (5, 'request accept')])),
                ('wallet', models.IntegerField(choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')])),
                ('change_time', models.DateTimeField()),
                ('deposit_before', models.FloatField()),
                ('deposit_after', models.FloatField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Request')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWalletCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.IntegerField(choices=[(0, 'rial wallet'), (1, 'dollar wallet'), (2, 'euro wallet')])),
                ('charge_time', models.DateTimeField()),
                ('deposit_before', models.FloatField()),
                ('deposit_after', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWalletTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.IntegerField(choices=[(0, 'rial wallet'), (1, 'dollar wallet'), (2, 'euro wallet')])),
                ('destination', models.IntegerField(choices=[(0, 'rial wallet'), (1, 'dollar wallet'), (2, 'euro wallet')])),
                ('transfer_time', models.DateTimeField()),
                ('source_deposit_before', models.FloatField()),
                ('source_deposit_after', models.FloatField()),
                ('destination_deposit_before', models.FloatField()),
                ('destination_deposit_after', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('genuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.GenUser')),
                ('company_rial_credit', models.FloatField()),
                ('company_dollar_cent_credit', models.FloatField()),
                ('company_euro_cent_credit', models.FloatField()),
                ('company_account_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('main.genuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
