# Generated by Django 2.0.6 on 2018-07-29 07:22

from django.db import migrations


def add_manager(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    manager_group = Group.objects.get(name='manager')
    Manager = apps.get_model('manager', 'Manager')
    manager = Manager(username= 'manager', email = 'manager@manager.com')
    manager.set_password('managermanager')
    manager_group.user_set.add(manager)

    manager.save()

class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180627_0658'),
    ]

    operations = [migrations.RunPython(add_manager)
    ]
