# Generated by Django 2.0.6 on 2018-07-29 07:22
from django.contrib.auth.hashers import make_password
from django.db import migrations

def add_manager(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    manager_group = Group.objects.get(name='manager')
    Manager = apps.get_model('manager', 'Manager')
    try:
        manager = Manager.objects.get(username= 'manager', email = 'manager@manager.com')
    except:
        manager = Manager(username= 'manager', email = 'manager@manager.com', company_rial_credit = 12, company_dollar_cent_credit = 342, company_euro_cent_credit = 324, company_account_number = "134123123")
        manager.password = make_password('managermanager')
        manager.save()
        manager_group.user_set.add(manager)

def remove_manager(apps,schema_editor):
    Manager = apps.get_model('manager', 'Manager')
    try:
        manager = Manager.objects.get(username= 'manager')
        manager.delete()
    except:
        pass    
    
class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20180627_0658'),
        ('main', '0006_auto_20180729_0709')
    ]

    operations = [
        migrations.RunPython(add_manager, remove_manager)
    ]
