# Generated by Django 2.0.3 on 2018-06-03 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genuser',
            name='polymorphic_ctype',
        ),
    ]
