# Generated by Django 2.0.6 on 2018-06-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_genuser_polymorphic_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='genuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Employee'), (2, 'Manager')], default=0),
        ),
    ]
