# Generated by Django 2.0.6 on 2018-08-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180816_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='state',
            field=models.IntegerField(choices=[(0, 'seen'), (1, 'unseen')], default=1),
            preserve_default=False,
        ),
    ]
