# Generated by Django 2.0.3 on 2018-08-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180816_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genuser',
            name='persian_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='genuser',
            name='persian_last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='genuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='genuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Customer'), (1, 'Employee'), (2, 'Manager')], default=0),
        ),
    ]
