# Generated by Django 2.0.6 on 2018-06-27 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_genuser_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.IntegerField(choices=[(0, 'rial'), (1, 'dollar'), (2, 'euro')])),
                ('time', models.DateTimeField()),
                ('is_profit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.GenUser')),
            ],
        ),
    ]
