# Generated by Django 2.0.6 on 2018-08-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180816_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
