# Generated by Django 2.0.6 on 2018-07-29 07:09

from django.db import migrations
from django.contrib.auth.admin import User


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.bulk_create([
        Group(name=u'employee'),
        Group(name=u'customer'),
        Group(name=u'manager'),
        Group(name=u'staff'),
        Group(name=u'wallet_user'),
    ])
def remove_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.all().delete()

def add_admin(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'newadmin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('adminadmin')
    superuser.save()
def remove_admin(apps,schema_editor):
    User.objects.get(username = "newadmin")

def add_transactions(apps, schema_editor):
    ""

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_walletchange'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups),
        migrations.RunPython(add_admin,remove_admin)]
    
