# Generated by Django 2.0.6 on 2018-08-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='state',
        ),
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
