# Generated by Django 2.0.6 on 2018-07-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180729_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletchange',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
